---
name: "geodash.js 0.0.1"
path:
  geodash: "./src/geodash"
plugins:
  - base
  - legend
  - welcome
  - about
  - download
dependencies:
  production:
    project: []
    javascript:
      - "./src/js/main/*.js"
  test:
    javascript:
      - "./src/js/main/*.js"
      - "./src/js/polyfill/*.js"
